In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!pwd

/Users/suraj/vscode/freelancing/fiverr/nlp-disease-symptom-ml/research/notebooks


In [3]:
train_path = "../../data/training.csv"
test_path = "../../data/testing.csv"

In [4]:
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

In [6]:
df = pd.concat([train_df,test_df])
df.shape, train_df.shape, test_df.shape

((4961, 133), (4920, 133), (41, 133))

In [24]:
pd.options.display.max_seq_items = 2000

In [25]:
df.drop(columns=['disease'],axis=0).columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition',
       'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety',
       'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness',
       'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough',
       'high_fever', 'sunken_eyes', 'breathlessness', 'sweating',
       'dehydration', 'indigestion', 'headache', 'yellowish_skin',
       'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes',
       'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea',
       'mild_fever', 'yellow_urine', 'yellowing_of_eyes',
       'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach',
       'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision',
       'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure',
 

In [46]:
X = df.drop(columns=['disease'],axis=0).values
y = df['disease'].values
len(X), len

(4961, <function len(obj, /)>)

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15,random_state = 32)

In [49]:
len(y_train), len(y_test)

(4216, 745)

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [40]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [31]:
# rf.predict(X_test)


pandas.core.frame.DataFrame

In [68]:
def evaluate_model(model,name=''):
    print('==='*20)
    print(name)
    # print('==='*20)
    y_pred = model.predict(X_test)
    print('Accuracy: ',accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

In [59]:
rf = RandomForestClassifier()
svc = SVC()
knn = KNeighborsClassifier(n_neighbors = 5)
dtc = DecisionTreeClassifier()

In [60]:
rf.fit(X_train,y_train)
svc.fit(X_train,y_train)
knn.fit(X_train,y_train)
dtc.fit(X_train,y_train)


DecisionTreeClassifier()

In [69]:
evaluate_model(rf,"Random Forest")
evaluate_model(svc, "SVC")
evaluate_model(knn,"KNN")
evaluate_model(dtc,"Decision Tree")

Random Forest
Accuracy:  1.0
[[21  0  0 ...  0  0  0]
 [ 0 15  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 13]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        21
                                   AIDS       1.00      1.00      1.00        15
                                   Acne       1.00      1.00      1.00        19
                    Alcoholic hepatitis       1.00      1.00      1.00        19
                                Allergy       1.00      1.00      1.00        19
                              Arthritis       1.00      1.00      1.00        17
                       Bronchial Asthma       1.00      1.00      1.00        27
                   Cervical spondylosis       1.00      1.00      1.00        20
                            Chicken pox       1.00      1.00      1.00        22
    

## Approach to NLP problem
**Preprocess Text**
- Lowercasing
- Tokenization
- removing stopwords and punctuation
- Lemmatization (real root word) or Stemming (break word)

**Text to Numeric**
- Bag of words
- CountVectorizer
- Tfidf